### ISSUE TITLE
TestAfkakClientIntegration.test_roundtrip_large_request intermittent failures

### ISSUE THREAD

**Issue by twm** [ciena/afkak#31]
The integration test `afkak.test.test_client_integration.TestAfkakClientIntegration.test_roundtrip_large_request` intermittently fails with `NotLeaderForPartitionError`:

```
Traceback (most recent call last):
  File "/home/travis/build/ciena/afkak/afkak/test/testutil.py", line 87, in wrapper
    return func(self)
  File "/home/travis/build/ciena/afkak/.tox/py35-int-snappy/lib/python3.5/site-packages/nose/twistedtools.py", line 169, in wrapper
    raise exc_type(exc_value).with_traceback(tb)
  File "/home/travis/build/ciena/afkak/.tox/py35-int-snappy/lib/python3.5/site-packages/nose/twistedtools.py", line 143, in errback
    failure.raiseException()
  File "/home/travis/build/ciena/afkak/.tox/py35-int-snappy/lib/python3.5/site-packages/twisted/python/failure.py", line 385, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/home/travis/build/ciena/afkak/.tox/py35-int-snappy/lib/python3.5/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/travis/build/ciena/afkak/.tox/py35-int-snappy/lib/python3.5/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/travis/build/ciena/afkak/afkak/test/test_client_integration.py", line 131, in test_roundtrip_large_request
    produce_resp, = yield self.client.send_produce_request([produce])
  File "/home/travis/build/ciena/afkak/.tox/py35-int-snappy/lib/python3.5/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/travis/build/ciena/afkak/afkak/client.py", line 463, in send_produce_request
    returnValue(self._handle_responses(resps, fail_on_error, callback))
  File "/home/travis/build/ciena/afkak/afkak/client.py", line 564, in _handle_responses
    check_error(resp)
  File "/home/travis/build/ciena/afkak/afkak/common.py", line 300, in check_error
    raise error(responseOrErrcode)
afkak.common.NotLeaderForPartitionError: ProduceResponse(topic='test_roundtrip_large_request-lomJaTsqwi', partition=0, error=6, offset=-1)
```

https://travis-ci.org/ciena/afkak/jobs/412822017

Or with `UnknownTopicOrPartitionError`:

```
Traceback (most recent call last):
  File "/home/travis/build/ciena/afkak/afkak/test/testutil.py", line 87, in wrapper
    return func(self)
  File "/home/travis/build/ciena/afkak/.tox/py35-int-snappy/lib/python3.5/site-packages/nose/twistedtools.py", line 169, in wrapper
    raise exc_type(exc_value).with_traceback(tb)
  File "/home/travis/build/ciena/afkak/.tox/py35-int-snappy/lib/python3.5/site-packages/nose/twistedtools.py", line 143, in errback
    failure.raiseException()
  File "/home/travis/build/ciena/afkak/.tox/py35-int-snappy/lib/python3.5/site-packages/twisted/python/failure.py", line 385, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/home/travis/build/ciena/afkak/.tox/py35-int-snappy/lib/python3.5/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/travis/build/ciena/afkak/.tox/py35-int-snappy/lib/python3.5/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/travis/build/ciena/afkak/afkak/test/test_client_integration.py", line 131, in test_roundtrip_large_request
    produce_resp, = yield self.client.send_produce_request([produce])
  File "/home/travis/build/ciena/afkak/.tox/py35-int-snappy/lib/python3.5/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/travis/build/ciena/afkak/afkak/client.py", line 463, in send_produce_request
    returnValue(self._handle_responses(resps, fail_on_error, callback))
  File "/home/travis/build/ciena/afkak/afkak/client.py", line 564, in _handle_responses
    check_error(resp)
  File "/home/travis/build/ciena/afkak/afkak/common.py", line 300, in check_error
    raise error(responseOrErrcode)
afkak.common.UnknownTopicOrPartitionError: ProduceResponse(topic='test_roundtrip_large_request-JjyTDqjQBS', partition=0, error=3, offset=-1)
```

https://travis-ci.org/ciena/afkak/jobs/412822019#L581
https://travis-ci.org/ciena/afkak/jobs/412822025#L584

**Comment by rthille** [comment]
```
2018-08-10 00:24:05,504 DEBUG client.py:292: <KafkaClient clientId=afkak.test.test_client_integration brokers=[('127.0.0.1', 36629), ('127.0.0.1', 52063), ('127.0.0.1', 55693)] timeout=2.5>: Broker/Topic metadata: {0: BrokerMetadata(node_id=0, host='127.0.0.1', port=36629), 1: BrokerMetadata(node_id=1, host='127.0.0.1', port=55693), 2: BrokerMetadata(node_id=2, host='127.0.0.1', port=52063)}/{'test_roundtrip_large_request-MCBIjEiGCH': TopicMetadata(topic='test_roundtrip_large_request-MCBIjEiGCH', topic_error_code=0, partition_metadata={0: PartitionMetadata(topic='test_roundtrip_large_request-MCBIjEiGCH', partition=0, partition_error_code=0, leader=2, replicas=(2, 0, 1), isr=(2, 0, 1)), 1: PartitionMetadata(topic='test_roundtrip_large_request-MCBIjEiGCH', partition=1, partition_error_code=0, leader=0, replicas=(0, 1, 2), isr=(0, 1, 2))})}
```
That shows that the partition exists and is supposedly sync'd to all replicas.
The test then recognizes that the partition exists and is ready and attempts to send to it:
```
2018-08-10 00:24:05,509 INFO testutil.py:127: Topic test_roundtrip_large_request-MCBIjEiGCH exists. Partition metadata: [PartitionMetadata(topic='test_roundtrip_large_request-MCBIjEiGCH', partition=0, partition_error_code=0, leader=2, replicas=(2, 0, 1), isr=(2, 0, 1)),
 PartitionMetadata(topic='test_roundtrip_large_request-MCBIjEiGCH', partition=1, partition_error_code=0, leader=0, replicas=(0, 1, 2), isr=(0, 1, 2))]
2018-08-10 00:24:05,508 DEBUG service.py:73: [2018-08-10 00:24:05,458] DEBUG [Replica Manager on Broker 1]: Partition [__consumer_offsets,1] received fetch request from follower 0 (kafka.server.ReplicaManager)
2018-08-10 00:24:05,509 DEBUG service.py:73: [2018-08-10 00:24:05,458] DEBUG [Replica Manager on Broker 1]: Partition [__consumer_offsets,1] received fetch request from follower 0 (kafka.server.ReplicaManager)
2018-08-10 00:24:05,509 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG [KafkaApi-1] Record follower log end offsets: Map([__consumer_offsets,16] -> 0 [0 : 0], [__consumer_offsets,49] -> 0 [0 : 0], [__consumer_offsets,28] -> 0 [0 : 0], [__consumer_offsets,7] -> 0 [0 : 0], [__consumer_offsets,4] -> 0 [0 : 0], [__consumer_offsets,13] -> 0 [0 : 0], [__consumer_offsets,40] -> 0 [0 : 0], [__consumer_offsets,37] -> 0 [0 : 0], [test_produce_large_request-DYqrnlsllJ,1] -> 0 [0 : 0], [__consumer_offsets,34] -> 0 [0 : 0], [__consumer_offsets,22] -> 1 [0 : 118], [__consumer_offsets,25] -> 0 [0 : 0], [__consumer_offsets,10] -> 0 [0 : 0], [__consumer_offsets,31] -> 0 [0 : 0], [__consumer_offsets,19] -> 0 [0 : 0], [__consumer_offsets,46] -> 0 [0 : 0], [__consumer_offsets,43] -> 0 [0 : 0], [__consumer_offsets,1] -> 0 [0 : 0])  (kafka.server.KafkaApis)
2018-08-10 00:24:05,510 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG [KafkaApi-1] Record follower log end offsets: Map([__consumer_offsets,16] -> 0 [0 : 0], [__consumer_offsets,49] -> 0 [0 : 0], [__consumer_offsets,28] -> 0 [0 : 0], [__consumer_offsets,7] -> 0 [0 : 0], [__consumer_offsets,4] -> 0 [0 : 0], [__consumer_offsets,13] -> 0 [0 : 0], [__consumer_offsets,40] -> 0 [0 : 0], [__consumer_offsets,37] -> 0 [0 : 0], [test_produce_large_request-DYqrnlsllJ,1] -> 0 [0 : 0], [__consumer_offsets,34] -> 0 [0 : 0], [__consumer_offsets,22] -> 1 [0 : 118], [__consumer_offsets,25] -> 0 [0 : 0], [__consumer_offsets,10] -> 0 [0 : 0], [__consumer_offsets,31] -> 0 [0 : 0], [__consumer_offsets,19] -> 0 [0 : 0], [__consumer_offsets,46] -> 0 [0 : 0], [__consumer_offsets,43] -> 0 [0 : 0], [__consumer_offsets,1] -> 0 [0 : 0])  (kafka.server.KafkaApis)
2018-08-10 00:24:05,510 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG Partition [__consumer_offsets,16] on broker 1: Skipping update high watermark since Old hw 0 [0 : 0] is larger than new hw 0 [0 : 0] for partition [__consumer_offsets,16]. All leo's are 0 [0 : 0] (kafka.cluster.Partition)
2018-08-10 00:24:05,510 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG Partition [__consumer_offsets,16] on broker 1: Skipping update high watermark since Old hw 0 [0 : 0] is larger than new hw 0 [0 : 0] for partition [__consumer_offsets,16]. All leo's are 0 [0 : 0] (kafka.cluster.Partition)
2018-08-10 00:24:05,510 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG [Replica Manager on Broker 1]: Recorded follower 0 position 0 for partition [__consumer_offsets,16]. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,510 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG [Replica Manager on Broker 1]: Recorded follower 0 position 0 for partition [__consumer_offsets,16]. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,510 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG [Replica Manager on Broker 1]: Request key [__consumer_offsets,16] unblocked 0 producer requests. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,510 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG [Replica Manager on Broker 1]: Request key [__consumer_offsets,16] unblocked 0 producer requests. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,510 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG Partition [__consumer_offsets,49] on broker 1: Skipping update high watermark since Old hw 0 [0 : 0] is larger than new hw 0 [0 : 0] for partition [__consumer_offsets,49]. All leo's are 0 [0 : 0] (kafka.cluster.Partition)
2018-08-10 00:24:05,510 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG Partition [__consumer_offsets,49] on broker 1: Skipping update high watermark since Old hw 0 [0 : 0] is larger than new hw 0 [0 : 0] for partition [__consumer_offsets,49]. All leo's are 0 [0 : 0] (kafka.cluster.Partition)
2018-08-10 00:24:05,510 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG [Replica Manager on Broker 1]: Recorded follower 0 position 0 for partition [__consumer_offsets,49]. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,511 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG [Replica Manager on Broker 1]: Recorded follower 0 position 0 for partition [__consumer_offsets,49]. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,511 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG [Replica Manager on Broker 1]: Request key [__consumer_offsets,49] unblocked 0 producer requests. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,511 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG [Replica Manager on Broker 1]: Request key [__consumer_offsets,49] unblocked 0 producer requests. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,511 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG Partition [__consumer_offsets,28] on broker 1: Skipping update high watermark since Old hw 0 [0 : 0] is larger than new hw 0 [0 : 0] for partition [__consumer_offsets,28]. All leo's are 0 [0 : 0] (kafka.cluster.Partition)
2018-08-10 00:24:05,511 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG Partition [__consumer_offsets,28] on broker 1: Skipping update high watermark since Old hw 0 [0 : 0] is larger than new hw 0 [0 : 0] for partition [__consumer_offsets,28]. All leo's are 0 [0 : 0] (kafka.cluster.Partition)
2018-08-10 00:24:05,511 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG [Replica Manager on Broker 1]: Recorded follower 0 position 0 for partition [__consumer_offsets,28]. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,511 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG [Replica Manager on Broker 1]: Recorded follower 0 position 0 for partition [__consumer_offsets,28]. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,511 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG [Replica Manager on Broker 1]: Request key [__consumer_offsets,28] unblocked 0 producer requests. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,511 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG [Replica Manager on Broker 1]: Request key [__consumer_offsets,28] unblocked 0 producer requests. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,511 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG Partition [__consumer_offsets,7] on broker 1: Skipping update high watermark since Old hw 0 [0 : 0] is larger than new hw 0 [0 : 0] for partition [__consumer_offsets,7]. All leo's are 0 [0 : 0] (kafka.cluster.Partition)
2018-08-10 00:24:05,511 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG Partition [__consumer_offsets,7] on broker 1: Skipping update high watermark since Old hw 0 [0 : 0] is larger than new hw 0 [0 : 0] for partition [__consumer_offsets,7]. All leo's are 0 [0 : 0] (kafka.cluster.Partition)
2018-08-10 00:24:05,511 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG [Replica Manager on Broker 1]: Recorded follower 0 position 0 for partition [__consumer_offsets,7]. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,512 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG [Replica Manager on Broker 1]: Recorded follower 0 position 0 for partition [__consumer_offsets,7]. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,512 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG [Replica Manager on Broker 1]: Request key [__consumer_offsets,7] unblocked 0 producer requests. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,512 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG [Replica Manager on Broker 1]: Request key [__consumer_offsets,7] unblocked 0 producer requests. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,512 DEBUG service.py:73: [2018-08-10 00:24:05,459] DEBUG Partition [__consumer_offsets,4] on broker 1: Skipping update high watermark since Old hw 0 [0 : 0] is larger than new hw 0 [0 : 0] for partition [__consumer_offsets,4]. All leo's are 0 [0 : 0] (kafka.cluster.Partition)
2018-08-10 00:24:05,512 DEBUG test_client_integration.py:125: Timestamp Before ProduceRequest
2018-08-10 00:24:05,512 DEBUG test_client_integration.py:129: Timestamp After ProduceRequest
2018-08-10 00:24:05,513 DEBUG client.py:759: _mrtb: sending request: 64 to broker: <KafkaBrokerClient 127.0.0.1:52063 clientId='afkak.test.test_client_integration' connected>
^^^^^^^^^^^^^^^^^^^^^^^^ Produce request sent ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2018-08-10 00:24:05,512 DEBUG service.py:73: [2018-08-10 00:24:05,347] DEBUG [Replica Manager on Broker 2]: Request key [__consumer_offsets,2] unblocked 0 producer requests. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,515 DEBUG service.py:73: [2018-08-10 00:24:05,347] DEBUG [Replica Manager on Broker 2]: Request key [__consumer_offsets,2] unblocked 0 producer requests. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,515 DEBUG service.py:73: [2018-08-10 00:24:05,347] DEBUG Partition [__consumer_offsets,14] on broker 2: Skipping update high watermark since Old hw 0 [0 : 0] is larger than new hw 0 [0 : 0] for partition [__consumer_offsets,14]. All leo's are 0 [0 : 0] (kafka.cluster.Partition)
2018-08-10 00:24:05,515 DEBUG service.py:73: [2018-08-10 00:24:05,347] DEBUG Partition [__consumer_offsets,14] on broker 2: Skipping update high watermark since Old hw 0 [0 : 0] is larger than new hw 0 [0 : 0] for partition [__consumer_offsets,14]. All leo's are 0 [0 : 0] (kafka.cluster.Partition)
2018-08-10 00:24:05,515 DEBUG service.py:73: [2018-08-10 00:24:05,347] DEBUG [Replica Manager on Broker 2]: Recorded follower 0 position 0 for partition [__consumer_offsets,14]. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,515 DEBUG service.py:73: [2018-08-10 00:24:05,347] DEBUG [Replica Manager on Broker 2]: Recorded follower 0 position 0 for partition [__consumer_offsets,14]. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,515 DEBUG service.py:73: [2018-08-10 00:24:05,347] DEBUG [Replica Manager on Broker 2]: Request key [__consumer_offsets,14] unblocked 0 producer requests. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,515 DEBUG service.py:73: [2018-08-10 00:24:05,347] DEBUG [Replica Manager on Broker 2]: Request key [__consumer_offsets,14] unblocked 0 producer requests. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,515 DEBUG service.py:73: [2018-08-10 00:24:05,347] DEBUG Partition [test_produce_request-aVRwCwUbBR,0] on broker 2: Skipping update high watermark since Old hw 0 [0 : 0] is larger than new hw -1 [0 : 0] for partition [test_produce_request-aVRwCwUbBR,0]. All leo's are 5 [0 : 335],-1 [0 : 0],0 [0 : 0] (kafka.cluster.Partition)
2018-08-10 00:24:05,515 DEBUG service.py:73: [2018-08-10 00:24:05,347] DEBUG Partition [test_produce_request-aVRwCwUbBR,0] on broker 2: Skipping update high watermark since Old hw 0 [0 : 0] is larger than new hw -1 [0 : 0] for partition [test_produce_request-aVRwCwUbBR,0]. All leo's are 5 [0 : 335],-1 [0 : 0],0 [0 : 0] (kafka.cluster.Partition)
2018-08-10 00:24:05,516 DEBUG service.py:73: [2018-08-10 00:24:05,347] DEBUG [Replica Manager on Broker 2]: Recorded follower 0 position 0 for partition [test_produce_request-aVRwCwUbBR,0]. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,516 DEBUG service.py:73: [2018-08-10 00:24:05,347] DEBUG [Replica Manager on Broker 2]: Recorded follower 0 position 0 for partition [test_produce_request-aVRwCwUbBR,0]. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,516 DEBUG service.py:73: [2018-08-10 00:24:05,347] DEBUG [Replica Manager on Broker 2]: Request key [test_produce_request-aVRwCwUbBR,0] unblocked 0 producer requests. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,516 DEBUG service.py:73: [2018-08-10 00:24:05,347] DEBUG [Replica Manager on Broker 2]: Request key [test_produce_request-aVRwCwUbBR,0] unblocked 0 producer requests. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,516 DEBUG service.py:73: [2018-08-10 00:24:05,347] DEBUG Partition [__consumer_offsets,26] on broker 2: Skipping update high watermark since Old hw 0 [0 : 0] is larger than new hw 0 [0 : 0] for partition [__consumer_offsets,26]. All leo's are 0 [0 : 0] (kafka.cluster.Partition)
2018-08-10 00:24:05,516 DEBUG service.py:73: [2018-08-10 00:24:05,347] DEBUG Partition [__consumer_offsets,26] on broker 2: Skipping update high watermark since Old hw 0 [0 : 0] is larger than new hw 0 [0 : 0] for partition [__consumer_offsets,26]. All leo's are 0 [0 : 0] (kafka.cluster.Partition)
2018-08-10 00:24:05,516 DEBUG service.py:73: [2018-08-10 00:24:05,347] DEBUG [Replica Manager on Broker 2]: Recorded follower 0 position 0 for partition [__consumer_offsets,26]. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,516 DEBUG service.py:73: [2018-08-10 00:24:05,347] DEBUG [Replica Manager on Broker 2]: Recorded follower 0 position 0 for partition [__consumer_offsets,26]. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,516 DEBUG service.py:73: [2018-08-10 00:24:05,347] DEBUG [Replica Manager on Broker 2]: Request key [__consumer_offsets,26] unblocked 0 producer requests. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,517 DEBUG service.py:73: [2018-08-10 00:24:05,347] DEBUG [Replica Manager on Broker 2]: Request key [__consumer_offsets,26] unblocked 0 producer requests. (kafka.server.ReplicaManager)
2018-08-10 00:24:05,517 DEBUG service.py:73: [2018-08-10 00:24:05,356] DEBUG [KafkaApi-2] Returning fetch response 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 for fetch request with correlation id 12 to client ReplicaFetcherThread-0-2 (kafka.server.KafkaApis)
2018-08-10 00:24:05,517 DEBUG service.py:73: [2018-08-10 00:24:05,356] DEBUG [KafkaApi-2] Returning fetch response 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 for fetch request with correlation id 12 to client ReplicaFetcherThread-0-2 (kafka.server.KafkaApis)
2018-08-10 00:24:05,517 DEBUG service.py:73: [2018-08-10 00:24:05,362] DEBUG Completed request:Name: FetchRequest; Version: 0; CorrelationId: 12; ClientId: ReplicaFetcherThread-0-2; ReplicaId: 0; MaxWait: 500 ms; MinBytes: 1 bytes from client /127.0.0.1:36648;totalTime:22,requestQueueTime:4,localTime:16,remoteTime:0,responseQueueTime:1,sendTime:1 (kafka.request.logger)
2018-08-10 00:24:05,517 ERROR client.py:566: Error found in response: ProduceResponse(topic='test_roundtrip_large_request-MCBIjEiGCH', partition=0, error=6, offset=-1)
```

**Comment by rthille** [comment]
In summary, Kafka == 💩
