### ISSUE TITLE
TestFailover.test_switch_leader intermittent failures

### ISSUE THREAD

**Issue by twm** [ciena/afkak#32]
The `afkak.test.test_failover_integration.TestFailover.test_switch_leader` tests fails intermittently with the following message:

```
Traceback (most recent call last):
  File "/home/travis/build/ciena/afkak/afkak/test/testutil.py", line 87, in wrapper
    return func(self)
  File "/home/travis/build/ciena/afkak/.tox/py35-int-snappy/lib/python3.5/site-packages/nose/twistedtools.py", line 169, in wrapper
    raise exc_type(exc_value).with_traceback(tb)
  File "/home/travis/build/ciena/afkak/.tox/py35-int-snappy/lib/python3.5/site-packages/nose/twistedtools.py", line 143, in errback
    failure.raiseException()
  File "/home/travis/build/ciena/afkak/.tox/py35-int-snappy/lib/python3.5/site-packages/twisted/python/failure.py", line 385, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/home/travis/build/ciena/afkak/.tox/py35-int-snappy/lib/python3.5/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/travis/build/ciena/afkak/afkak/test/test_failover_integration.py", line 141, in test_switch_leader
    self.assertEqual(count, 22 * index)
AssertionError: 20 != 22
```

https://travis-ci.org/ciena/afkak/jobs/414207454

**Comment by twm** [comment]
https://travis-ci.org/ciena/afkak/jobs/422361116
https://travis-ci.org/ciena/afkak/jobs/422361121
