### ISSUE TITLE
Python 3.6, 3.7 support

### ISSUE THREAD

**Issue by lahwran** [ciena/afkak#63]
What's the status of py3.6 and py3.7 support? I see there's a prerelease build in the releases list that mentions WIP py3 support, but the readme in the repository only says it supports 3.5. Should I expect any issues with 3.6/3.7?

**Comment by twm** [comment]
We are currently running the tests against 3.6. I ran the unit tests against 3.7 and hit this failure (presumably [PEP 479](https://www.python.org/dev/peps/pep-0479/)):

```
======================================================================
ERROR: test_decode_message_set_stop_iteration (afkak.test.test_kafkacodec.TestKafkaCodec)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../afkak/kafkacodec.py", line 133, in _decode_message_set_iter
    ((offset, ), cur) = relative_unpack('>q', data, cur)
  File ".../afkak/_util.py", line 155, in relative_unpack
    raise BufferUnderflowError("Not enough data left")
afkak.common.BufferUnderflowError: Not enough data left

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../afkak/kafkacodec.py", line 153, in _decode_message_set_iter
    raise StopIteration()
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../afkak/test/test_kafkacodec.py", line 323, in test_decode_message_set_stop_iteration
    msgs = list(KafkaCodec._decode_message_set_iter(encoded))
RuntimeError: generator raised StopIteration
```

I'll fix this right away.

Note that Python 3 support is only present in master at the moment. I want to merge #51 before issuing a 3.0 as it is a major change with public API impact (it requires changing things that are public API surface but probably shouldn't have been). We are using a snapshot of current master internally without issue, but that is on Python 2.7.
