### ISSUE TITLE
TestAfkakClientIntegration.test_roundtrip_large_request assertion error

### ISSUE THREAD

**Issue by twm** [ciena/afkak#66]
Continuing on from #31...

```
FAIL: afkak.test.test_client_integration.TestAfkakClientIntegration.test_roundtrip_large_request
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ciena/afkak/afkak/test/testutil.py", line 88, in wrapper
    return func(self)
  File "/home/travis/build/ciena/afkak/.tox/py27-int-snappy-murmur/lib/python2.7/site-packages/nose/twistedtools.py", line 143, in errback
    failure.raiseException()
  File "/home/travis/build/ciena/afkak/.tox/py27-int-snappy-murmur/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/travis/build/ciena/afkak/afkak/test/test_client_integration.py", line 128, in test_roundtrip_large_request
    self.assertEqual(len(messages), 1)
AssertionError: 0 != 1
```

Seen once. Python 2.7, Kafka 1.1.1.

**Comment by twm** [comment]
I'm now seeing this quite frequently on Travis and occasionally even locally.

**Comment by rthille** [comment]
I wonder if that's just timing, or if the test is broken, or if Kafka isn't providing the guaranties we think it does...

**Comment by twm** [comment]
It looks like the timeout is only 1 second, so no wonder this fails on Travis now that the topic is autocreated right before the test:

https://github.com/ciena/afkak/blob/0738c1fcd4a221a1c5a876e7d197bb4ab2ae7b2b/afkak/test/int/test_client_integration.py#L113-L114
